# Generated by Django 3.1.7 on 2021-09-17 14:30

import Server.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=Server.storage.OverwriteStorage(), upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('Sym_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sym_name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
